require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GxClassesController do

  # This should return the minimal set of attributes required to create a valid
  # GxClass. As you add validations to GxClass, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GxClassesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all gx_classes as @gx_classes" do
      gx_class = GxClass.create! valid_attributes
      get :index, {}, valid_session
      assigns(:gx_classes).should eq([gx_class])
    end
  end

  describe "GET show" do
    it "assigns the requested gx_class as @gx_class" do
      gx_class = GxClass.create! valid_attributes
      get :show, {:id => gx_class.to_param}, valid_session
      assigns(:gx_class).should eq(gx_class)
    end
  end

  describe "GET new" do
    it "assigns a new gx_class as @gx_class" do
      get :new, {}, valid_session
      assigns(:gx_class).should be_a_new(GxClass)
    end
  end

  describe "GET edit" do
    it "assigns the requested gx_class as @gx_class" do
      gx_class = GxClass.create! valid_attributes
      get :edit, {:id => gx_class.to_param}, valid_session
      assigns(:gx_class).should eq(gx_class)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GxClass" do
        expect {
          post :create, {:gx_class => valid_attributes}, valid_session
        }.to change(GxClass, :count).by(1)
      end

      it "assigns a newly created gx_class as @gx_class" do
        post :create, {:gx_class => valid_attributes}, valid_session
        assigns(:gx_class).should be_a(GxClass)
        assigns(:gx_class).should be_persisted
      end

      it "redirects to the created gx_class" do
        post :create, {:gx_class => valid_attributes}, valid_session
        response.should redirect_to(GxClass.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gx_class as @gx_class" do
        # Trigger the behavior that occurs when invalid params are submitted
        GxClass.any_instance.stub(:save).and_return(false)
        post :create, {:gx_class => {  }}, valid_session
        assigns(:gx_class).should be_a_new(GxClass)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GxClass.any_instance.stub(:save).and_return(false)
        post :create, {:gx_class => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gx_class" do
        gx_class = GxClass.create! valid_attributes
        # Assuming there are no other gx_classes in the database, this
        # specifies that the GxClass created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GxClass.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => gx_class.to_param, :gx_class => { "these" => "params" }}, valid_session
      end

      it "assigns the requested gx_class as @gx_class" do
        gx_class = GxClass.create! valid_attributes
        put :update, {:id => gx_class.to_param, :gx_class => valid_attributes}, valid_session
        assigns(:gx_class).should eq(gx_class)
      end

      it "redirects to the gx_class" do
        gx_class = GxClass.create! valid_attributes
        put :update, {:id => gx_class.to_param, :gx_class => valid_attributes}, valid_session
        response.should redirect_to(gx_class)
      end
    end

    describe "with invalid params" do
      it "assigns the gx_class as @gx_class" do
        gx_class = GxClass.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GxClass.any_instance.stub(:save).and_return(false)
        put :update, {:id => gx_class.to_param, :gx_class => {  }}, valid_session
        assigns(:gx_class).should eq(gx_class)
      end

      it "re-renders the 'edit' template" do
        gx_class = GxClass.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GxClass.any_instance.stub(:save).and_return(false)
        put :update, {:id => gx_class.to_param, :gx_class => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gx_class" do
      gx_class = GxClass.create! valid_attributes
      expect {
        delete :destroy, {:id => gx_class.to_param}, valid_session
      }.to change(GxClass, :count).by(-1)
    end

    it "redirects to the gx_classes list" do
      gx_class = GxClass.create! valid_attributes
      delete :destroy, {:id => gx_class.to_param}, valid_session
      response.should redirect_to(gx_classes_url)
    end
  end

end
