require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GxClassSetsController do

  # This should return the minimal set of attributes required to create a valid
  # GxClassSet. As you add validations to GxClassSet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GxClassSetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all gx_class_sets as @gx_class_sets" do
      gx_class_set = GxClassSet.create! valid_attributes
      get :index, {}, valid_session
      assigns(:gx_class_sets).should eq([gx_class_set])
    end
  end

  describe "GET show" do
    it "assigns the requested gx_class_set as @gx_class_set" do
      gx_class_set = GxClassSet.create! valid_attributes
      get :show, {:id => gx_class_set.to_param}, valid_session
      assigns(:gx_class_set).should eq(gx_class_set)
    end
  end

  describe "GET new" do
    it "assigns a new gx_class_set as @gx_class_set" do
      get :new, {}, valid_session
      assigns(:gx_class_set).should be_a_new(GxClassSet)
    end
  end

  describe "GET edit" do
    it "assigns the requested gx_class_set as @gx_class_set" do
      gx_class_set = GxClassSet.create! valid_attributes
      get :edit, {:id => gx_class_set.to_param}, valid_session
      assigns(:gx_class_set).should eq(gx_class_set)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GxClassSet" do
        expect {
          post :create, {:gx_class_set => valid_attributes}, valid_session
        }.to change(GxClassSet, :count).by(1)
      end

      it "assigns a newly created gx_class_set as @gx_class_set" do
        post :create, {:gx_class_set => valid_attributes}, valid_session
        assigns(:gx_class_set).should be_a(GxClassSet)
        assigns(:gx_class_set).should be_persisted
      end

      it "redirects to the created gx_class_set" do
        post :create, {:gx_class_set => valid_attributes}, valid_session
        response.should redirect_to(GxClassSet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gx_class_set as @gx_class_set" do
        # Trigger the behavior that occurs when invalid params are submitted
        GxClassSet.any_instance.stub(:save).and_return(false)
        post :create, {:gx_class_set => {  }}, valid_session
        assigns(:gx_class_set).should be_a_new(GxClassSet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GxClassSet.any_instance.stub(:save).and_return(false)
        post :create, {:gx_class_set => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gx_class_set" do
        gx_class_set = GxClassSet.create! valid_attributes
        # Assuming there are no other gx_class_sets in the database, this
        # specifies that the GxClassSet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GxClassSet.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => gx_class_set.to_param, :gx_class_set => { "these" => "params" }}, valid_session
      end

      it "assigns the requested gx_class_set as @gx_class_set" do
        gx_class_set = GxClassSet.create! valid_attributes
        put :update, {:id => gx_class_set.to_param, :gx_class_set => valid_attributes}, valid_session
        assigns(:gx_class_set).should eq(gx_class_set)
      end

      it "redirects to the gx_class_set" do
        gx_class_set = GxClassSet.create! valid_attributes
        put :update, {:id => gx_class_set.to_param, :gx_class_set => valid_attributes}, valid_session
        response.should redirect_to(gx_class_set)
      end
    end

    describe "with invalid params" do
      it "assigns the gx_class_set as @gx_class_set" do
        gx_class_set = GxClassSet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GxClassSet.any_instance.stub(:save).and_return(false)
        put :update, {:id => gx_class_set.to_param, :gx_class_set => {  }}, valid_session
        assigns(:gx_class_set).should eq(gx_class_set)
      end

      it "re-renders the 'edit' template" do
        gx_class_set = GxClassSet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GxClassSet.any_instance.stub(:save).and_return(false)
        put :update, {:id => gx_class_set.to_param, :gx_class_set => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gx_class_set" do
      gx_class_set = GxClassSet.create! valid_attributes
      expect {
        delete :destroy, {:id => gx_class_set.to_param}, valid_session
      }.to change(GxClassSet, :count).by(-1)
    end

    it "redirects to the gx_class_sets list" do
      gx_class_set = GxClassSet.create! valid_attributes
      delete :destroy, {:id => gx_class_set.to_param}, valid_session
      response.should redirect_to(gx_class_sets_url)
    end
  end

end
